n=input("\nEnter Name : ")
h=float(input("Enter The Height : "))
m=float(input("Enter The Weight : "))
bmi=(m/(h**2))
f=open("E:\Bhanu.txt","a+")
f.write("%s:"%n)
f.write("%f"%bmi)
f.write("\n")
f.close()
